### ISSUE TITLE
OpenLayers 5 improvements

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#1563]
# TOOLS
- [ ] Google navigation - werkt op het uit/aan zetten van zoom
- [ ] Border navigation
- [ ] Zoom
- [ ] Super pan en pan doen nu beide hetzelfde in OL5
- [ ] Coordinate link window
-------------------------
# COMPONENT
- [ ] Cyclorama images
- [ ] Edit Bulk
- [ ] Fireworks Permit
- [ ] Graph (niet getest, zou gewoon moeten werken)
- [ ] Influence area (niet kunnen testen)
- [ ] Overview map
- [ ] snapping - Zit er wel in (alleen niet met meten?)
- [ ] Tekenen - kan je nog niet de andere symbolen dan een punt tekenen(driehoek, vierkant etc.).
# LAYERS
-------
- [ ] ARC services
#TODO (tasks)
------------
- [ ] Dode code opruimen (deels gedaan, kom steeds vaker dode code tegen)
- [ ] Goed commentaar toevoegen
- [ ] Kijken of andere sprites werken

**Comment by deRightDirection** [comment]
mogelijk het gebruik van vector tiles?
