### ISSUE TITLE
library updates

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#620]
Flamingo is built using a large number of 3rd party libraries, some of these have not been updated in a long time though the projects maintaining and developing those libraries have release new versions.

A quick list (using `mvn -U org.codehaus.mojo:versions-maven-plugin:2.3:display-dependency-updates > updates.log` command, you can run a quick CVE scan using: `mvn -U org.owasp:dependency-check-maven:1.4.3:check > cve-scan.log`):

  - [x] #619 com.google.javascript:closure-compiler ......... rr2079.1 -> v20160619 
  - [x] #652 com.google.javascript:closure-compiler ......... v20160619 -> v20160713 
  - [x] #632 com.googlecode.json-simple:json-simple ...... 1.1 -> 1.1.1
  - [x] #621 commons-fileupload:commons-fileupload ..... 1.3 -> 1.3.2
  - [x] javax.mail:javax.mail-api ........................................ 1.5.2 -> 1.5.5
  - [x] #667 javax.mail:javax.mail-api ................................1.5.5 -> 1.5.6
  - [x] org.hsqldb:hsqldb ................................................... 2.3.3 -> 2.3.4
  - [x] #623 org.apache.poi:poi ........................................ 3.9 -> 3.14
  - [x] #623 org.apache.poi:poi-ooxml .............................. 3.9 -> 3.14
  - [x] #633 org.quartz-scheduler:quartz ........................... 2.1.5 -> 2.2.3
  - [ ] #595 Solr upgrade
    - org.apache.lucene:lucene-core ..................... 4.6.0 -> 6.1.0
    - org.apache.solr:solr-core ............................... 4.6.0 -> 6.1.0
    - org.apache.solr:solr-solrj ................................ 4.6.0 -> 6.1.0
  - [x] #641 org.json:json ................................... 20090211 -> 20160212
  - [x] #658 org.json:json ................................... 20160212 -> 20160807
  - [x] #668 org.json:json ................................... 20160807 -> 20160810
  - [x] #669 org.mockito:mockito-all .......................... 1.8.4 -> 2.0.2-beta
  - [x] #669 org.powermock:powermock-api-mockito ................... 1.5.5 -> 1.6.5
  - [x] #669 org.powermock:powermock-module-junit4 ................ 1.5.5 -> 1.6.5
  - [x] #661 org.geotools:gt- <all> ......................................... 14.4 -> 14.5
  - [ ] #602 org.geotools:gt- <all> ......................................... 14.x -> 16.x
  - [x] #659 xalan:xalan ........................................... 2.7.0 -> 2.7.2 (NB. [CVE-2014-0107](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-0107))
  - [x] #659 xerces:xercesImpl .................................... 2.7.1 -> 2.11.0
  - [x] #659 org.apache.xmlgraphics:fop ................................ 1.0 -> 2.1 (NB, [CVE-2015-0250](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-0250))
  - [x] #670 commons-beanutils:commons-beanutils-core .............. 1.8.0 -> 1.8.3
  - [x] #671 commons-io:commons-io ..................................... 2.1 -> 2.5
  - [x] #673 commons-logging:commons-logging ......................... 1.1.1 -> 1.2
  - [x] #672 org.apache.commons:commons-lang3 .......................... 3.1 -> 3.4
  - [x] #687 net.sourceforge.stripes:stripes ............ 1.5.6 -> 1.7.0-async-beta
  - [x] #687 org.stripesstuff:stripesstuff ......................... 0.4.1 -> 1.0.3
  - [ ] #674 nl.b3p:b3p-commons-csw .................................. 2.0 -> 4.2.2
  - [ ] #nnn org.eclipse.emf:org.eclipse.emf.common ... 2.10.1 -> 2.11.0-v20150805-0538
  - [ ] #710 Hibernate
    - org.hibernate:hibernate-core .............. 3.6.8.Final -> 5.2.2.Final
    - org.hibernate:hibernate-entitymanager ..... 3.6.8.Final -> 5.2.2.Final

Note some of these upgrades require a java runtime upgrade as well.

**Comment by mprins** [comment]
closing as most of these have been fixed and any remaining have an issue of their own to track the upgrade
